version: "3.9"

services:
  frontend:
    restart: always
    build:
      dockerfile: Dockerfile.dev
    container_name: xtream_assignment
    ports:
      - 5173
    volumes:
      - .:/app
    networks:
      - xtream-network

networks:
  xtream-network:
    driver: bridge
