FROM node:20.11.1-alpine


LABEL version="1.0"
LABEL description="React frontend for xtream code assignment"


WORKDIR /app


COPY ./package.json .


RUN npm install


COPY . .

EXPOSE 5173

CMD [ "npm", "run", "dev" ]